Avg order value = DIVIDE([Total Revenue], [Total Orders])
Total Orders = COUNTROWS(Sales)
Total Revenue = SUM(Sales[Sales Amount]) 
Average Unit Price = AVERAGE(Sales[Unit Price])
Total Extended Amount = SUM(Sales[Extended Amount])
Total Product Cost New = SUM(Sales[Product Standard Cost])
count City = COUNT(Reseller[City]) 